### ISSUE TITLE
Contiformer wont load config with Python 3.11 : annotation @configclass not supported 

### ISSUE THREAD

**Issue by scoutant** [microsoft/PhysioPro#20]
Using Python 3.11.
Installation and contiformer example as mentioned :
pip install .
python -m physiopro.entry.train docs/configs/contiformer_tpp.yml

Traceback (most recent call last):
  File "   PhysioPro/physiopro/entry/train.py", line 13, in <module>
    @configclass
     ^^^^^^^^^^^
  File "   anaconda3/lib/python3.11/site-packages/utilsd/config/python.py", line 126, in configclass
    cls = dataclass(cls)
          ^^^^^^^^^^^^^^
  File "anaconda3/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'utilsd.config.builtin.RuntimeConfig'> for field runtime is not allowed: use default_factory

This does not happen when installing physiopro in Python 3.8, 3.9 or 3.10 environnements.

**Comment by chenyuqi990215** [comment]
Please use Python 3.10, thanks.

**Comment by suiguoxin** [comment]
Fixed in #21
