### ISSUE TITLE
Bug: utilsd went wrong with physiopro.dataset.classification

### ISSUE THREAD

**Issue by kerry0120** [microsoft/PhysioPro#20]
I want to simply load a dataset with physiopro.dataset.classification.
Following is my test.yml and test_entry.py.
```
data:
  type: classification
  data_folder: /D_data/v-yike/public_processed_tusz_v2.0.0_complete_12s/unipolar
  meta_path: /D_data/v-yike/public_processed_tusz_v2.0.0_complete_12s/unipolar/meta.pkl
runtime:
  seed: 42
  use_cuda: true

``` 

```python
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

from utilsd import get_output_dir, get_checkpoint_dir, setup_experiment
from utilsd.experiment import print_config
from utilsd.config import PythonConfig, RegistryConfig, RuntimeConfig, configclass

from physiopro.dataset import DATASETS

import torch

@configclass
class ForecastConfig(PythonConfig):
    data: RegistryConfig[DATASETS]
    runtime: RuntimeConfig = RuntimeConfig()


def run_train(config):
    setup_experiment(config.runtime)
    print_config(config)
    trainset = config.data.build(dataset="train")
    preprocessor = trainset.get_preprocessor()
    testset = config.data.build(dataset="test", preprocessor=preprocessor)
    dataloader = torch.utils.data.DataLoader(trainset, batch_size=1, shuffle=False, num_workers=0)
    print(len(dataloader))


if __name__ == "__main__":
    _config = ForecastConfig.fromcli()
    run_train(_config)

``` 

Here is the troubleshooting:
```
Traceback (most recent call last):
  File "/home/v-yike/miniconda3/envs/p38/lib/python3.8/site-packages/utilsd/config/type_def.py", line 185, in load
    converted = t.from_plain(payload, ctx)
  File "/home/v-yike/miniconda3/envs/p38/lib/python3.8/site-packages/utilsd/config/type_def.py", line 563, in from_plain
    return super().from_plain(plain, ctx, type_=self.inner_type)
  File "/home/v-yike/miniconda3/envs/p38/lib/python3.8/site-packages/utilsd/config/type_def.py", line 485, in from_plain
    raise TypeError(f'Expect a dict or dataclass, but found {type(plain)}: {plain}')
TypeError: Expect a dict or dataclass, but found <class 'NoneType'>: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/v-yike/miniconda3/envs/p38/lib/python3.8/site-packages/utilsd/config/type_def.py", line 397, in _try_types
    return TypeDef.load(types[0], plain, ctx=ctx)
  File "/home/v-yike/miniconda3/envs/p38/lib/python3.8/site-packages/utilsd/config/type_def.py", line 194, in load
    raise ValidationError(err_message)
utilsd.config.exception.ValidationError: Object can not be loaded. Cause: Expect a dict or dataclass, but found <class 'NoneType'>: None
  Parser location: data -> preprocessor
  Matched types: union -> union:utilsd.config.registry.ClassConfig[physiopro.dataset.preprocessor.Preprocessor] -> classconfig
  Object: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/v-yike/miniconda3/envs/p38/lib/python3.8/site-packages/utilsd/config/type_def.py", line 397, in _try_types
    return TypeDef.load(types[0], plain, ctx=ctx)
  File "/home/v-yike/miniconda3/envs/p38/lib/python3.8/site-packages/utilsd/config/type_def.py", line 195, in load
    raise TypeError(f'No hook found for type: {type}')
TypeError: No hook found for type: <class 'physiopro.dataset.preprocessor.Preprocessor'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/v-yike/miniconda3/envs/p38/lib/python3.8/site-packages/utilsd/config/type_def.py", line 397, in _try_types
    return TypeDef.load(types[0], plain, ctx=ctx)
  File "/home/v-yike/miniconda3/envs/p38/lib/python3.8/site-packages/utilsd/config/type_def.py", line 195, in load
    raise TypeError(f'No hook found for type: {type}')
TypeError: No hook found for type: <class 'NoneType'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/v-yike/miniconda3/envs/p38/lib/python3.8/site-packages/utilsd/config/type_def.py", line 185, in load
    converted = t.from_plain(payload, ctx)
  File "/home/v-yike/miniconda3/envs/p38/lib/python3.8/site-packages/utilsd/config/type_def.py", line 402, in from_plain
    return _try_types(self.inner_types)
  File "/home/v-yike/miniconda3/envs/p38/lib/python3.8/site-packages/utilsd/config/type_def.py", line 400, in _try_types
    return _try_types(types[1:])
  File "/home/v-yike/miniconda3/envs/p38/lib/python3.8/site-packages/utilsd/config/type_def.py", line 400, in _try_types
    return _try_types(types[1:])
  File "/home/v-yike/miniconda3/envs/p38/lib/python3.8/site-packages/utilsd/config/type_def.py", line 400, in _try_types
    return _try_types(types[1:])
  File "/home/v-yike/miniconda3/envs/p38/lib/python3.8/site-packages/utilsd/config/type_def.py", line 394, in _try_types
    raise TypeError(f'All possible types from union {self.inner_types} are exhausted.')
TypeError: All possible types from union [utilsd.config.registry.ClassConfig[physiopro.dataset.preprocessor.Preprocessor], <class 'physiopro.dataset.preprocessor.Preprocessor'>, <class 'NoneType'>] are exhausted.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 30, in <module>
    _config = ForecastConfig.fromcli()
  File "/home/v-yike/miniconda3/envs/p38/lib/python3.8/site-packages/utilsd/config/python.py", line 177, in _fromcli
    TypeDef.load(cls, default_config.asdict(), ParseContext(cli_context))
  File "/home/v-yike/miniconda3/envs/p38/lib/python3.8/site-packages/utilsd/config/type_def.py", line 185, in load
    converted = t.from_plain(payload, ctx)
  File "/home/v-yike/miniconda3/envs/p38/lib/python3.8/site-packages/utilsd/config/type_def.py", line 523, in from_plain
    value = TypeDef.load(field.type, value, ctx=ctx)
  File "/home/v-yike/miniconda3/envs/p38/lib/python3.8/site-packages/utilsd/config/type_def.py", line 185, in load
    converted = t.from_plain(payload, ctx)
  File "/home/v-yike/miniconda3/envs/p38/lib/python3.8/site-packages/utilsd/config/type_def.py", line 589, in from_plain
    return super().from_plain(plain, ctx, type_=dataclass)
  File "/home/v-yike/miniconda3/envs/p38/lib/python3.8/site-packages/utilsd/config/type_def.py", line 523, in from_plain
    value = TypeDef.load(field.type, value, ctx=ctx)
  File "/home/v-yike/miniconda3/envs/p38/lib/python3.8/site-packages/utilsd/config/type_def.py", line 194, in load
    raise ValidationError(err_message)
utilsd.config.exception.ValidationError: Object can not be loaded. Cause: All possible types from union [utilsd.config.registry.ClassConfig[physiopro.dataset.preprocessor.Preprocessor], <class 'physiopro.dataset.preprocessor.Preprocessor'>, <class 'NoneType'>] are exhausted.
  Parser location: data -> preprocessor
  Matched types: union
  Object: None
``` 
It seems utilsd have problem with Optional[Union[ClassConfig[Preprocessor], Preprocessor]] and inherit. Maybe a quick test could be done with this. Thx!

**Comment by chenyuqi990215** [comment]
One way to fix the bug might be to reinstall the latest version of utilsd. The codes are tested with `utilsd==0.0.15`.

**Comment by kerry0120** [comment]
> One way to fix the bug might be to reinstall the latest version of utilsd. The codes are tested with `utilsd==0.0.15`.

The problem is solved with utilsd==0.0.15, while it's utilsd==0.0.17 before.  So the version of utilsd in setup.py should be fixed? Since there is utilsd>=0.0.15
