### ISSUE TITLE
utilsd error

### ISSUE THREAD

**Issue by RichardShea** [microsoft/PhysioPro#26]
Hi,

I get the following error when running <br> `!python -m physiopro.entry.train docs/configs/contiformer_mask_classification.yml --data.mask_ratio 0.3 --data.name Heartbeat` :

_Traceback (most recent call last):
  File "/content/PhysioPro/utilsd/config/type_def.py", line 186, in load
    t.validate(converted, ctx)
  File "/content/PhysioPro/utilsd/config/type_def.py", line 135, in validate
    typeguard.check_type(f'{converted} ({ctx.current_name})', converted, self.type)
TypeError: check_type() takes 2 positional arguments but 3 were given_

Did a function in utilsd package change?

Thank you,

Richard

**Comment by JasonNerd** [comment]
confused too, and now `utilsd` disappearred?Moreover, why i cannot downald the dataset. http://www.timeseriesclassification.com/aeon-toolkit/Archives/Multivariate2018_ts.zip is not accessible(403 forbidden). are there any other ways to downald the data or can you share with me?

**Comment by chenyuqi990215** [comment]
Hi, thanks for asking and sorry for the late reply. `check_type()` take 2 positional arguments after python 3.10, while 3 arguments before python 3.10. One simple way to fix the issue is to create a new environment with python=3.8.

> Hi,
> 
> I get the following error when running `!python -m physiopro.entry.train docs/configs/contiformer_mask_classification.yml --data.mask_ratio 0.3 --data.name Heartbeat` :
> 
> _Traceback (most recent call last): File "/content/PhysioPro/utilsd/config/type_def.py", line 186, in load t.validate(converted, ctx) File "/content/PhysioPro/utilsd/config/type_def.py", line 135, in validate typeguard.check_type(f'{converted} ({ctx.current_name})', converted, self.type) TypeError: check_type() takes 2 positional arguments but 3 were given_
> 
> Did a function in utilsd package change?
> 
> Thank you,
> 
> Richard

Hi, thanks for asking and sorry for the late reply. `check_type()` take 2 positional arguments after python 3.10, while 3 arguments before python 3.10. One simple way to fix the issue is to create a new environment with python=3.8.

**Comment by chenyuqi990215** [comment]
> confused too, and now `utilsd` disappearred?Moreover, why i cannot downald the dataset. http://www.timeseriesclassification.com/aeon-toolkit/Archives/Multivariate2018_ts.zip is not accessible(403 forbidden). are there any other ways to downald the data or can you share with me?

Thanks for your question. You can try to open VPN before downloading the dataset. `utilsd` can be simply downloaded with `pip install utilsd==0.0.18.post0`.
